[theme]
name = "brutalist-blueprint"
description = "A brutalist documentation theme for BHC"
license = "MIT"
homepage = "https://bhc.arcanist.sh"
min_version = "0.18.0"

[author]
name = "arcanist.sh"
homepage = "https://arcanist.sh"

[extra]
